# docker-compose.yml (Development)
services:
  db:
    image: postgres:15-alpine
    container_name: django_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=football_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web_dev
    command: gunicorn api_football.wsgi:application --bind 0.0.0.0:8000 --workers 2 --reload --timeout 120 --log-level debug
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_ENV=development

  nginx:
    image: nginx:alpine
    container_name: django_nginx_dev
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data_dev:
  static_volume:
  media_volume: