# Generated by Django 5.2.6 on 2025-11-02 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flag', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='football_data.country')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('national', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, null=True)),
                ('venue_id', models.IntegerField(unique=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_capacity', models.IntegerField(blank=True, null=True)),
                ('venue_surface', models.CharField(blank=True, max_length=50, null=True)),
                ('venue_address', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_image', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football_data.country')),
                ('league', models.ForeignKey(db_column='league_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football_data.league')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
            },
        ),
    ]
