# Generated by Django 5.2.6 on 2025-11-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO code or API-provided unique country code', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Country name', max_length=100)),
                ('flag', models.URLField(blank=True, help_text='URL to the country flag', null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.IntegerField(help_text='Unique league ID from API', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='League name', max_length=100)),
                ('type', models.CharField(help_text='Type of league (e.g., League or Cup)', max_length=50)),
                ('logo', models.URLField(blank=True, help_text='URL to league logo', null=True)),
                ('country', models.ForeignKey(db_column='country_code', help_text='Country that the league belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='football_data.country')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'db_table': 'league',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(help_text='Unique team ID from API', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the team', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Team code (if available)', max_length=10, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('national', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, null=True)),
                ('venue_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_capacity', models.IntegerField(blank=True, null=True)),
                ('venue_surface', models.CharField(blank=True, max_length=50, null=True)),
                ('venue_address', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_image', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(db_column='country_code', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football_data.country')),
                ('league', models.ForeignKey(db_column='league_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='football_data.league')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(help_text='Unique player ID from API', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of player from API', max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, help_text='First name of player from API', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, help_text='Last name of player from API', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, help_text='Age of player from API', null=True)),
                ('nationality', models.CharField(blank=True, help_text='Player nationaility from API. (Not the same as country ID)', max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, help_text='Player birth_place from API. (Not the same as country ID)', max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, help_text='Player birth_country from API. (Not the same as country ID)', max_length=100, null=True)),
                ('height', models.FloatField(blank=True, help_text='Player height in centimeters', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Player weight in kilograms', null=True)),
                ('birth_date', models.DateField(blank=True, help_text='Player birth date', null=True)),
                ('photo', models.URLField(blank=True, help_text="URL to player's photo", null=True)),
                ('postion', models.CharField(blank=True, help_text='Player position', max_length=50, null=True)),
                ('injured', models.BooleanField(default=False, help_text='Is the player injured?')),
                ('league', models.ForeignKey(db_column='league_id', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football_data.league')),
                ('team', models.ForeignKey(db_column='team_id', help_text='Team that the player belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football_data.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
                'ordering': ['name'],
            },
        ),
    ]
