# Generated by Django 5.2.6 on 2025-11-02 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='ISO code or API-provided unique country code', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, help_text='URL to the country flag', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Country name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.ForeignKey(db_column='country_code', help_text='Country that the league belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='football_data.country'),
        ),
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.IntegerField(help_text='Unique league ID from API', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.URLField(blank=True, help_text='URL to league logo', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(help_text='League name', max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='type',
            field=models.CharField(help_text='Type of league (e.g., League or Cup)', max_length=50),
        ),
    ]
