# Generated by Django 5.2.6 on 2025-11-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0002_alter_league_options_alter_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Country name', max_length=100),
        ),
    ]
