# Generated by Django 5.2.6 on 2025-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, help_text='Team code (if available)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(help_text='Unique team ID from API', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of the team', max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
