# Generated by Django 5.2.6 on 2025-11-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0004_alter_country_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='venue_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
