# Generated by Django 5.2.6 on 2025-11-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0005_alter_team_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, help_text='Team code (if available)', max_length=10, null=True),
        ),
    ]
